### ISSUE TITLE
Some bodies don't get a MoonstormContentManager, which causes NREs in BuffModuleBase.OnBuffsChanged

### ISSUE THREAD

**Issue by TheMysticSword** [TeamMoonstorm/MoonstormSharedUtils#45] opened 2023-07-04 08:05 UTC
I don't exactly know why that happens, but from the looks of it, it occurs most often on Nuxlar's Umbral Mithrix phase 2 & 3 time crystals.
Here's the part where it NREs, contentManager isn't null-checked.
https://github.com/TeamMoonstorm/MoonstormSharedUtils/blob/6f6352505cb0c02122fd395154e960f795b8b221/Runtime/Code/Classes/ModuleBases/MainModules/BuffModuleBase.cs#L122
https://github.com/TeamMoonstorm/MoonstormSharedUtils/blob/6f6352505cb0c02122fd395154e960f795b8b221/Runtime/Code/Classes/ModuleBases/MainModules/BuffModuleBase.cs#L123

**Comment by Nebby1999** [comment] 2023-07-04 13:32
Y'know, I have no idea what the fuck nuxlar is doing.

MSU takes ALL the characterbodies on the BodyCatalog and adds the ContentManager component to them. Every single character in the catalog has it.

My only guess is that nuxlar is not making his crystals added to the CharacterBody catalog. And I don't want to null check the content manager component because again, it's added to all characters on the catalog after it gets initialized. If his crystals aren't in the catalog then well. That's not an issue on my part, but an issue on his.

Closing this as not planned.

**Closed** 2023-07-04 13:32 UTC

**Comment by Phreelosu** [comment] 2023-07-06 10:15
Nebby this occurs on Distant Roost upon killing Birdsharks too, this exact issue
while true it isnt causing any cascading NRE chain but I mean, it does throw a massive wall of text and a good lagspike

**Comment by Nebby1999** [comment] 2023-07-06 14:39
:)

Why the fuck are birdsharks not on the fucking catalog

**Comment by Nebby1999** [comment] 2023-11-15 18:21
As a way to put this on an end instead of being completely in limbo.

Bird sharks are indeed in the catalog, as such they do have the component and nullrefs caused by it must be another mod's issue.

Speaking about other mod's issues, the issue with umbral mithrix has been fixed on Nuxlar's side, turns out he didn't add a prefab to the contentpack, and as such the MSU content manager didn't add the component to the cloned prefab

Adiós
