### ISSUE TITLE
MSU 0.5.0 Crash on Start-up Log

### ISSUE THREAD

**Issue by Scrublord1337** [TeamMoonstorm/MoonstormSharedUtils#9] opened 2021-11-08 20:32 UTC
New MSU update broke something. Here's the log. Only SS2 Nightly, LIT, and MSU + it's dependencies installed.
[MSU 0.5.0 Crash.txt](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/7499962/MSU.0.5.0.Crash.txt)

**Comment by kellianoy** [comment] 2021-11-08 22:20
Same for me. Same messages & all.

**Comment by Nebby1999** [comment] 2021-11-11 18:20
Duplicate of https://github.com/TeamMoonstorm/MoonstormSharedUtils/issues/8

For now, downgrade to MSU 0.4.1, this'll be fixed on version 0.5.1 of MSU.

**Closed by Nebby1999** 2021-11-11 18:20 UTC
Labels: duplicate
