### ISSUE TITLE
Massive amounts of NREs during Simulacrum while doing nothing

### ISSUE THREAD

**Issue by Phreelosu** [TeamMoonstorm/MoonstormSharedUtils#20] opened 2022-04-23 22:15 UTC
There seems to be some unknown NREs while playing Simulacrum
I haven't tested regular runs

These NREs dont seem to be causing any gameplay issues such as framerate drops or crashes, but they do spam the console a lot

Log:
[LogOutput.log](https://github.com/TeamMoonstorm/MoonstormSharedUtils/files/8548695/LogOutput.log)

**Comment by Nebby1999** [comment] 2022-04-23 23:19
At first glance i can see that the Start() method is failing, this would imply that the CharacterBody property of MoonstormContentManager is null, which means i'm not setting it properly, i'll probably fix it by doing it on awake instead, unsure yet.

This would also explain the problem with GetInterfaces method, as the Characterbody property is still used to reach the healthComponent's onIncomingDamageReceivers and onTakeDamageReceivers arrays

i'll check this out in a fix sometime soon, thanks for the report

**Comment by Nebby1999** [comment] 2022-04-24 14:34
Fixed in this [commit](https://github.com/TeamMoonstorm/MoonstormSharedUtils/commit/40dcdde0db3793699088a1ade11bc3d5148fc7e2), caused by the content manager having properties instead of fields

**Closed by Nebby1999** 2022-04-24 14:34 UTC
